#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-github-markup
Version  : 1.3.3
Release  : 3
URL      : https://rubygems.org/downloads/github-markup-1.3.3.gem
Source0  : https://rubygems.org/downloads/github-markup-1.3.3.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-github-markup-bin
BuildRequires : ruby
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-sanitize

%description
GitHub Markup
=============
rich text file. The generated HTML is then run through filters in the [html-pipeline](https://github.com/jch/html-pipeline) to perform things like [sanitization](#html-sanitization) and [syntax highlighting](https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/syntax_highlight_filter.rb).

%package bin
Summary: bin components for the rubygem-github-markup package.
Group: Binaries

%description bin
bin components for the rubygem-github-markup package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n github-markup-1.3.3
gem spec %{SOURCE0} -l --ruby > rubygem-github-markup.gemspec

%build
gem build rubygem-github-markup.gemspec

%install
gem_dir=$(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .${gem_dir} \
--bindir .%{_bindir} \
github-markup-1.3.3.gem

mkdir -p %{buildroot}${gem_dir}
cp -pa .${gem_dir}/* \
%{buildroot}${gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/github-markup-1.3.3.gem
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/CommandError/cdesc-CommandError.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/CommandImplementation/POSIX/cdesc-POSIX.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/CommandImplementation/block-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/CommandImplementation/call_block-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/CommandImplementation/cdesc-CommandImplementation.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/CommandImplementation/command-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/CommandImplementation/execute-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/CommandImplementation/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/CommandImplementation/render-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/CommandImplementation/sanitize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/GemImplementation/cdesc-GemImplementation.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/GemImplementation/gem_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/GemImplementation/load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/GemImplementation/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/GemImplementation/render-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/GemImplementation/renderer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/Implementation/cdesc-Implementation.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/Implementation/file_ext_regexp-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/Implementation/load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/Implementation/match%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/Implementation/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/Implementation/regexp-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/Implementation/render-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/Markdown/cdesc-Markdown.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/Markdown/load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/Markdown/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/Markdown/render-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/Markdown/try_require-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/RDoc/cdesc-RDoc.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/RDoc/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/RDoc/to_html-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/can_render%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/cdesc-Markup.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/command-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/markup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/markups-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/preload%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/render-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/Markup/renderer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/GitHub/cdesc-GitHub.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/Orgmode/cdesc-Orgmode.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/WikiCloth/cdesc-WikiCloth.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/github-markup-1.3.3/ri/lib/github/commands/page-rest2html.ri
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/.kick
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/.travis.yml
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/HISTORY.md
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/README.md
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/bin/github-markup
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/github-markup.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/lib/github-markup.rb
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/lib/github/commands/rest2html
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/lib/github/markup.rb
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/lib/github/markup/command_implementation.rb
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/lib/github/markup/gem_implementation.rb
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/lib/github/markup/implementation.rb
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/lib/github/markup/markdown.rb
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/lib/github/markup/rdoc.rb
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/lib/github/markups.rb
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/script/bootstrap
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/script/cibuild
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/test/fixtures/fail.sh
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/test/markup_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/test/markups/README.asciidoc
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/test/markups/README.asciidoc.html
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/test/markups/README.creole
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/test/markups/README.creole.html
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/test/markups/README.litcoffee
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/test/markups/README.litcoffee.html
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/test/markups/README.markdown
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/test/markups/README.markdown.html
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/test/markups/README.mediawiki
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/test/markups/README.mediawiki.html
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/test/markups/README.noformat
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/test/markups/README.noformat.html
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/test/markups/README.org
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/test/markups/README.org.html
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/test/markups/README.pod
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/test/markups/README.pod.html
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/test/markups/README.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/test/markups/README.rdoc.html
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/test/markups/README.rmd
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/test/markups/README.rmd.html
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/test/markups/README.rst
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/test/markups/README.rst.html
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/test/markups/README.rst.txt
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/test/markups/README.rst.txt.html
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/test/markups/README.textile
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/test/markups/README.textile.html
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/test/markups/README.toc.rst
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/test/markups/README.toc.rst.html
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/test/markups/README.txt
/usr/lib64/ruby/gems/2.2.0/gems/github-markup-1.3.3/test/markups/README.txt.html
/usr/lib64/ruby/gems/2.2.0/specifications/github-markup-1.3.3.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/github-markup
