#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-github-markup
Version  : 1.4.0
Release  : 6
URL      : https://rubygems.org/downloads/github-markup-1.4.0.gem
Source0  : https://rubygems.org/downloads/github-markup-1.4.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-github-markup-bin
BuildRequires : ruby
BuildRequires : rubygem-minitest
BuildRequires : rubygem-nokogiri
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-sanitize

%description
GitHub Markup
=============
This library is the first step of a journey that every markup file in a repository goes on before it is rendered on GitHub.com:

%package bin
Summary: bin components for the rubygem-github-markup package.
Group: Binaries

%description bin
bin components for the rubygem-github-markup package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n github-markup-1.4.0
gem spec %{SOURCE0} -l --ruby > rubygem-github-markup.gemspec

%build
gem build rubygem-github-markup.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
github-markup-1.4.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/github-markup-1.4.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/.kick
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/HISTORY.md
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/README.md
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/bin/github-markup
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/github-markup.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/lib/github-markup.rb
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/lib/github/commands/rest2html
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/lib/github/markup.rb
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/lib/github/markup/command_implementation.rb
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/lib/github/markup/gem_implementation.rb
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/lib/github/markup/implementation.rb
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/lib/github/markup/markdown.rb
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/lib/github/markup/rdoc.rb
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/lib/github/markups.rb
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/script/bootstrap
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/script/cibuild
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/test/fixtures/fail.sh
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/test/markup_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/test/markups/README.asciidoc
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/test/markups/README.asciidoc.html
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/test/markups/README.creole
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/test/markups/README.creole.html
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/test/markups/README.litcoffee
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/test/markups/README.litcoffee.html
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/test/markups/README.markdown
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/test/markups/README.markdown.html
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/test/markups/README.mediawiki
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/test/markups/README.mediawiki.html
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/test/markups/README.noformat
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/test/markups/README.noformat.html
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/test/markups/README.org
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/test/markups/README.org.html
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/test/markups/README.pod
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/test/markups/README.pod.html
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/test/markups/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/test/markups/README.rdoc.html
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/test/markups/README.rmd
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/test/markups/README.rmd.html
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/test/markups/README.rst
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/test/markups/README.rst.html
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/test/markups/README.rst.txt
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/test/markups/README.rst.txt.html
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/test/markups/README.textile
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/test/markups/README.textile.html
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/test/markups/README.toc.rst
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/test/markups/README.toc.rst.html
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/test/markups/README.txt
/usr/lib64/ruby/gems/2.3.0/gems/github-markup-1.4.0/test/markups/README.txt.html
/usr/lib64/ruby/gems/2.3.0/specifications/github-markup-1.4.0.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/github-markup
